name: skimage-workbooks
channels:
  - conda-forge
dependencies:
  - python
  - mystmd
  - ipykernel
  - jupyter-server
  - setuptools
  - numpy
  - scipy
  - sympy
  - pooch
  - matplotlib
  - pillow
  - pandas
  - tabulate
  - cython
  - diplib
  - pip
  - pip:
      - "scikit-image@git+https://github.com/scikit-image/scikit-image@main"
      - "opencv-python-headless"
